name:                timetravel
version:             0.1.0.0
github:              "cdupont/timetravel"
license:             BSD3
author:              "Corentin Dupont"
maintainer:          "corentin.dupont@gmail.com"
copyright:           "2021 Corentin Dupont"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/timetravel#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams
- diagrams-lib
- diagrams-svg
- diagrams-core
- reanimate
- reanimate-svg
- fgl
- containers
- linear
- colour
- palette
- extra
- utility-ht 
- bytestring
- svg-builder
- string-conversions
- text 
- optparse-simple
- matrix
- vector
- control-monad-omega
- split
- brick >= 0.69.1

library:
  source-dirs: src

executables:
  timetravel-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timetravel

tests:
  timetravel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timetravel
